version: '3'
 
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
 
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./drf_api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
 
volumes:
  postgres_data:
